// Built-in starter scenarios so the user can practise immediately without
// authoring anything ("無劇情也能代入"). Titles/descriptions are in the UI
// language (繁中); target phrases are in the practice language. Stable ids: once
// a default is practised it is saved under the same id and then drops out of the
// "範例情境" list (no duplicate).

import { FRAME_PRESETS } from "./frames";
import type { Scenario, TargetLanguage } from "../../kernel/types";

export const DEFAULT_SCENARIOS: Record<TargetLanguage, Scenario[]> = {
  en: [
    {
      id: "def-en-1on1",
      title: "和美國同事一對一",
      targetLanguage: "en",
      level: "B1",
      baseContext: FRAME_PRESETS.en,
      contentContext: "你和一位美國同事進行每週一對一，要更新工作進度並提出一個遇到的問題。",
      coachRole: "美國同事 Alex",
      userRole: "你（台灣團隊成員）",
      objectives: ["清楚更新本週進度", "提出並說明一個問題", "回答後續提問"],
      targetPhrases: ["Let me walk you through…", "I'm running into an issue with…", "Could we sync on…?"],
    },
    {
      id: "def-en-client",
      title: "向客戶說明方案",
      targetLanguage: "en",
      level: "B1",
      baseContext: FRAME_PRESETS.en,
      contentContext: "電話會議中向外國客戶說明你的提案並處理疑問。",
      coachRole: "外國客戶",
      userRole: "你（提案方）",
      objectives: ["說明方案重點", "處理反對意見", "確認下一步"],
      targetPhrases: ["The key benefit is…", "I understand your concern, however…", "Let's align on next steps."],
    },
    {
      id: "def-en-deadline",
      title: "協商交付期限",
      targetLanguage: "en",
      level: "B1",
      baseContext: FRAME_PRESETS.en,
      contentContext: "和海外 PM 協商一個比較緊的交付期限。",
      coachRole: "海外專案經理",
      userRole: "你",
      objectives: ["說明現實限制", "提出替代方案", "達成共識"],
      targetPhrases: ["Realistically, we can…", "Would it work if…?", "Let's find a middle ground."],
    },
    {
      id: "def-en-standup",
      title: "每日站會更新",
      targetLanguage: "en",
      level: "B1",
      baseContext: FRAME_PRESETS.en,
      contentContext: "英文 standup，簡短報告昨天做了什麼、今天要做什麼、有什麼阻礙。",
      coachRole: "Scrum master",
      userRole: "你",
      objectives: ["三段式簡短報告", "用過去式講昨天", "清楚說出阻礙"],
      targetPhrases: ["Yesterday I…", "Today I'm going to…", "I'm blocked on…"],
    },
    {
      id: "def-en-gartner",
      title: "Gartner 顧問會議：AI 治理主題的英語對談",
      targetLanguage: "en",
      level: "B1",
      baseContext: FRAME_PRESETS.en,
      contentContext:
        "你參加一場 Gartner 顧問交流會議。螢幕主題是「金融業中代理型 AI 的治理與風險」，但這次練習重點是會議中的英語口說流暢度，不是技術細節。你以與會者身分自我介紹、向分析師提出一個問題、分享一段簡短看法、沒聽懂時請對方再說明，最後禮貌道謝收尾。",
      coachRole: "Gartner 的分析師（資深顧問），主持交流、歡迎你發言、回答提問並引導你輪流互動",
      userRole: "來自台灣金融業的與會者，對 AI 治理有興趣，前來參與討論",
      objectives: [
        "用一兩句話自然自我介紹，說明職務與來這場會議的興趣",
        "向分析師清楚提出一個開放式問題，讓對話順暢延續",
        "用簡短句子分享看法，適度表達同意或不同意",
        "沒聽清楚或不確定時，禮貌地請對方再說明一次",
        "發言結束時自然道謝收尾，維持對話流暢節奏",
      ],
      targetPhrases: [
        "Hi, I'm Wei from a bank in Taiwan, and I'm really interested in this topic.",
        "Thanks for having me. Can I ask you a quick question?",
        "I was wondering, how do you usually see companies start with this?",
        "That's a really interesting point.",
        "I'd actually agree with that, but I see it a little differently.",
        "Sorry, could you say that again? I didn't quite catch it.",
        "Just to make sure I understand, do you mean...?",
        "Thank you so much, that was really helpful.",
      ],
    },
    {
      id: "def-en-consultant",
      title: "和顧問聊聊 LLM 供應商怎麼選",
      targetLanguage: "en",
      level: "B1",
      baseContext: FRAME_PRESETS.en,
      contentContext:
        "你約了一位企業顧問輕鬆聊天。公司想開始用 AI 語言模型（LLM），但供應商很多還沒決定。這不是技術深談，而是放鬆的對話練習：你用簡單方式說明大概想找什麼、請顧問分享看法、把幾個選項用白話比較、問幾個後續問題，最後一起講好下一步。重點是把話講順、把對話接下去。",
      coachRole: "友善、健談的企業顧問，會主動分享看法、舉簡單例子，並反問你問題、引導你把想法說清楚",
      userRole: "公司裡負責了解 AI 工具的窗口，向顧問請教、蒐集意見",
      objectives: [
        "用一兩句話簡單開場，說明今天想聊什麼、在找什麼樣的方案",
        "向顧問請教意見，用簡單的話把幾個選項做比較（例如價格、好不好上手）",
        "表達自己的看法，適時同意或不同意，讓對話自然往下走",
        "聽不懂或想確認時，自然地請對方再說一次或換句話說",
        "結尾整理重點、講好下一步，禮貌收尾",
      ],
      targetPhrases: [
        "Thanks for making the time. I wanted to pick your brain about a few things.",
        "We're just getting started, so I'm still figuring out what we actually need.",
        "What's your take on it? Which one would you go with?",
        "How does that one compare to the others, roughly speaking?",
        "That makes sense. I hadn't really thought about it that way.",
        "Sorry, could you say that part again? I want to make sure I follow.",
        "I see what you mean, but I'm not totally sure that fits us.",
        "So just to recap, the next step would be to put together a short list, right?",
      ],
    },
  ],
  ja: [
    {
      id: "def-ja-restaurant",
      title: "餐廳點餐",
      targetLanguage: "ja",
      level: "A2",
      baseContext: FRAME_PRESETS.ja,
      contentContext: "レストランで、おすすめを聞いてから料理を注文し、最後に会計する。",
      coachRole: "店員",
      userRole: "客（你）",
      objectives: ["おすすめを聞く", "料理を注文する", "会計を頼む"],
      targetPhrases: ["おすすめは何ですか", "これをください", "お会計お願いします"],
    },
    {
      id: "def-ja-ramen",
      title: "拉麵店點餐",
      targetLanguage: "ja",
      level: "A2",
      baseContext: FRAME_PRESETS.ja,
      contentContext: "ラーメン屋で注文する。トッピングや麺の硬さ、大盛りなどを伝える。",
      coachRole: "店員",
      userRole: "客（你）",
      objectives: ["ラーメンを注文する", "トッピングを追加する", "麺の硬さ・量を伝える"],
      targetPhrases: ["醤油ラーメンをください", "味玉を追加してください", "麺は固めで、大盛りで"],
    },
    {
      id: "def-ja-cafe",
      title: "咖啡廳點餐",
      targetLanguage: "ja",
      level: "A2",
      baseContext: FRAME_PRESETS.ja,
      contentContext: "カフェで飲み物を注文する。サイズ、ホット／アイス、店内か持ち帰りかを選ぶ。",
      coachRole: "店員",
      userRole: "客（你）",
      objectives: ["飲み物を注文する", "サイズとホット／アイスを選ぶ", "店内か持ち帰りかを答える"],
      targetPhrases: ["アイスコーヒーをください", "Mサイズでお願いします", "持ち帰りで／店内で"],
    },
    {
      id: "def-ja-conbini",
      title: "便利商店結帳",
      targetLanguage: "ja",
      level: "A2",
      baseContext: FRAME_PRESETS.ja,
      contentContext: "コンビニで会計をする。袋の要否や温めを確認される。",
      coachRole: "店員",
      userRole: "客（你）",
      objectives: ["会計をする", "袋を断る／もらう", "温めを頼む"],
      targetPhrases: ["お会計お願いします", "袋は大丈夫です", "温めてください"],
    },
    {
      id: "def-ja-usj",
      title: "USJ VIP 導覽：跟著工作人員玩大阪環球影城",
      targetLanguage: "ja",
      level: "A2",
      baseContext: FRAME_PRESETS.ja,
      contentContext:
        "你參加了大阪環球影城（USJ）的 VIP 導覽行程。一位日本導覽工作人員會帶你逐一參觀園區，介紹下一個設施和快速通關（エクスプレス・パス）的使用方式。你要跟工作人員打招呼、聽他介紹接下來要去的地方、表達自己最想先玩哪一項、詢問可不可以拍照、要排多久、附近有沒有餐廳，過程中還會輕鬆閒聊並在結束時道謝。",
      coachRole: "USJ 的日本導覽工作人員（ガイドさん），親切、講話清楚、會配合放慢速度",
      userRole: "參加 VIP 導覽的台灣觀光客，日文約 A2 程度",
      objectives: [
        "和導覽工作人員打招呼，並聽懂他介紹下一個設施與快速通關的安排",
        "用簡單句子表達自己最想先玩哪一個設施",
        "詢問可不可以拍照、大概要排多久隊",
        "詢問附近有沒有餐廳或可以吃午餐的地方",
        "在行程中做簡單的閒聊，並在結束時向工作人員道謝",
      ],
      targetPhrases: [
        "こんにちは、今日はよろしくお願いします。",
        "次はどこに行きますか？",
        "わたしは先にハリー・ポッターに乗りたいです。",
        "ここで写真を撮ってもいいですか？",
        "どのくらい並びますか？",
        "近くにレストランはありますか？",
        "エクスプレス・パスはどう使いますか？",
        "今日はとても楽しかったです。ありがとうございました。",
      ],
    },
    {
      id: "def-ja-luggage",
      title: "在旅館櫃台寄送行李到下一間飯店",
      targetLanguage: "ja",
      level: "A2",
      baseContext: FRAME_PRESETS.ja,
      contentContext:
        "你今天要退房，行李很多不想一路拖著走。你想拜託現在這間旅館的櫃台人員，幫你把行李配送到下一個目的地、也就是你今晚要入住的下一間旅館。你需要說明需求、確認他們是否能代為寄送、詢問費用大約多少以及行李大概什麼時候會送達，並提供下一間旅館的名稱與入住日期，最後道謝。",
      coachRole: "飯店櫃台接待人員（親切、會用簡單清楚的日文回應，必要時放慢速度）",
      userRole: "入住的旅客（A2 程度，想把行李寄到下一間旅館）",
      objectives: [
        "向櫃台說明想把行李寄送到下一間旅館的需求",
        "確認飯店是否可以代為寄送行李",
        "詢問寄送費用大約多少錢",
        "告知下一間旅館的名稱與入住日期，並詢問行李何時會送達",
        "完成委託並向櫃台人員道謝",
      ],
      targetPhrases: [
        "すみません、荷物を次のホテルに送りたいんですが。",
        "ここで荷物を送ってもらえますか。",
        "送料はいくらぐらいですか。",
        "次のホテルは「さくらホテル」です。",
        "チェックインは明日の予定です。",
        "荷物はいつごろ着きますか。",
        "お願いします。ありがとうございます。",
      ],
    },
  ],
};
